front-end/config/routes.rb
FrontEnd::Application.routes.draw do # The priority is based upon order of creation:

  root :to => 'news#index'

  post "training/classify" => 'training#classify', :as => 'classify'
  get "sentiment_analysis" => 'sentiment_analysis#index'

  match 'news/list'  => 'news#index'
  match 'news/:category'  => 'news#index'
  resources :news
  resources :training
end

front-end/app/models/category.rb
class Category
  include MongoMapper::Document
  set_collection_name "news_categories"
  key :name, String
end

front-end/app/models/news_item.rb
class NewsItem
  include MongoMapper::Document
end

front-end/app/models/training_data.rb
class TrainingData
  include MongoMapper::Document
  key :title, String
  key :transformed_text, String
  key :link, String
  key :published_date, Date
  key :category, String
  key :categorized, Boolean,:default => false

  def TrainingData.classify(news_item_id, category)
    news_item = find_by_id(news_item_id)
    news_item.set({:category => category})
    news_item.set({:categorized => true})
  end
end

front-end/app/models/tweet.rb
class Tweet
  include MongoMapper::Document
end

front-end/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

front-end/app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @categories = Category.all
    if params[:category]
      @current_category = params[:category]
      @news_items = NewsItem.where(:category => params[:category]).order(:publishedDate.desc)
    else
      @news_items = NewsItem.order(:published_date)
    end
  end
end

front-end/app/controllers/sentiment_analysis_controller.rb
class SentimentAnalysisController < ApplicationController
  def index
    @top_positive_tweets = Tweet.where(:category => "positive").limit(20).order(:score.desc)
    @top_negative_tweets = Tweet.where(:category => "negative").limit(20).order(:score.desc)
  end
end

front-end/app/controllers/training_controller.rb
class TrainingController < ApplicationController
  def index
    @training_data = TrainingData.where(:categorized => [nil, false]).all
    @categories = Category.all
  end

  def classify
    @news_item_id = params[:news_item_id]
    @category = params[:category]

    TrainingData.classify(@news_item_id, @category)
    redirect_to :action => :index
  end
end

front-end/app/helpers/application_helper.rb
module ApplicationHelper
end

front-end/app/helpers/news_helper.rb
module NewsHelper
end

front-end/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>tidings</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <link href='http://fonts.googleapis.com/css?family=Gentium+Book+Basic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

front-end/app/views/news/classify.erb
<%= @news_item_id %>
<%= @category %>

front-end/app/views/news/index.html.erb
<div class="container">
  <header class="hero-unit">
    <h1>tidings</h1>
  </header>
  <div class="bd row-fluid">
    <div class="main span8">
      <div class="featured well">
        <h3>Popular stories</h3>
        <ul class="thumbnails">
          <li class="span4">
            <a href="">
              <div class="thumbnail">
              <img src="http://placehold.it/300x200" alt="">
              <h3>London all set for paralympics</h3>
              <p>The British High Commissioner, Sir James Bevan, pointed at the slogan &hellip;</p>
            </div>
            </a>
          </li>
          <li class="span4">
            <a href="">
              <div class="thumbnail">
              <img src="http://placehold.it/300x200" alt="">
              <h3>London all set for paralympics</h3>
              <p>The British High Commissioner, Sir James Bevan, pointed at the slogan &hellip;</p>
            </div>
            </a>
          </li>
          <li class="span4">
            <a href="">
              <div class="thumbnail">
              <img src="http://placehold.it/300x200" alt="">
              <h3>London all set for paralympics</h3>
              <p>The British High Commissioner, Sir James Bevan, pointed at the slogan &hellip;</p>
            </div>
            </a>
          </li>
        </ul>
      </div>

      <div class="entries">
        <% items = @news_items.all %>
        <% items.each do |item| %>
          <div class="entry">
            <div class="row-fluid entry-hd">
              <div class="span6">
                <ul class="h-list">
                  <li><span class="badge badge-info">23</span> likes</li>
                  <li><span class="badge badge-info">11</span> shares</li>
                </ul>
              </div>
              <div class="span6 entry-published">
                <p><%= item.publishedDate %></p>
              </div>
            </div>

            <h1 class="h3"><%= link_to item.title, item.link, :target => "_blank" %></h1>
            <p class="entry-text"><%= item.transformedText[0..430] %></p>
            <p><%= link_to "read more", item.link, :target => "_blank" %></p>
            <div class="meta">
              <span class="label"><%= item.category %></span>  
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="aside span4">
      <form class="form-search well">
        <input type="text" class="input-medium search-query">
        <button type="submit" class="btn">Search</button>
      </form>
      <h3>Categories</h3>
      <ul class="nav nav-tabs nav-stacked">
        <% @categories.each do |category|%>
          <li class="<%= !@current_category.nil? && category.name.casecmp(@current_category) == 0 ? "active" : "" %>">
            <%= link_to category.name, :controller => "news", :category => category.name.downcase %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

front-end/app/views/sentiment_analysis/index.html.erb
<h1>Sentiment Analysis</h1>

<h2>What people are saying about <b>Apple</b></h2>

<h3>Positive</h3>
<ul>
<% @top_positive_tweets.each do |tweet| %>
  <li><%= "#{tweet.fullText}" %></li>
<% end %>
</ul>

<h3>Negative</h3>
<ul>
<% @top_negative_tweets.each do |tweet| %>
  <li><%= "#{tweet.fullText}" %></li>
<% end %>
</ul>

front-end/app/views/training/index.html.erb
<div class="container">
  <header class="jumbotron subhead">
  <h1>Classify</h1>
  </header>
  </br>
  <% @training_data.each do |item| %>
    <div class="container">
      <strong><%= item.title %></strong>
      </br>
      <p><%= item.transformedText %></p>
      <small><%= link_to "read more", item.link, :target => "_blank" %></small>
      <p><small><%= item.publishedDate %></small></p>
      <% @categories.each do |category|%>
        <%= button_to category.name, classify_path(:news_item_id => item.id, :category => category.name), :class => "btn" %>
      <% end %>
    </div>
  <% end %>
</div>